slice_filters:
    s: [0.7, 120.0]
select_filters:
    #quintiles: [0, 4]
    multipoles: [0,2]
statistics: ['voids']
data:
    observation: 
        class: 'AbacusCutSky'
        args:
            dataset: 'voidprior'
        get_obs_args:
            cosmology: 0
            hod_idx: 80
    covariance:
        class: 'Patchy'
        dataset: 'voidprior'
        add_emulator_error_test_set: false
        add_predicted_uncertainty: false
        add_simulation_error: false
        volume_scaling: 1
# fixed_parameters: ['w0_fld', 'wa_fld', 'nrun', 'N_ur'] 
fixed_parameters:  ['nrun', 'N_ur', 'w0_fld', 'wa_fld','logM_cut','sigma','logM1','alpha','kappa']
theory_model:
    module: 'sunbird.summaries'
    class: 'Bundle'
    args:
        dataset: 'voidprior'
        loss: 'mse'
        path_to_models: '/global/homes/t/tsfraser/fraser_fork/sunbird/trained_models/best/'
        flax: false
inference:
    output_dir: '/pscratch/sd/t/tsfaser/sunbird/chains/'
priors:
    stats_module: 'scipy.stats'
    omega_b:
        distribution: 'norm'
        mean: 0.02268
        dispersion: 0.00038
        #distribution: 'uniform'
        #min: 0.02100
        #max: 0.02500
    omega_cdm:
        distribution: 'uniform'
        min: 0.1032
        max: 0.140

    sigma8_m:
        distribution: 'uniform'
        min: 0.678
        max: 0.938
    n_s:
        distribution: 'uniform'
        min: 0.9012
        max: 1.025
    nrun:
        distribution: 'uniform'
        min: -0.038
        max: 0.038

    N_ur:
        distribution: 'uniform'
        min: 1.188
        max: 2.889

    w0_fld:
        distribution: 'uniform'
        min: -1.22
        max: -0.726

    wa_fld:
        distribution: 'uniform'
        min: -0.628
        max: 0.621
    logM_cut:
        distribution: 'uniform'
        min: 12
        max: 14.5
    logM1:
        distribution: 'uniform'
        min: 13
        max: 16
    alpha:
        distribution: 'uniform'
        min: 0.4
        max: 1.5
    sigma:
        distribution: 'uniform'
        min: 0.05
        max: 0.9
    kappa:
        distribution: 'uniform'
        min: 0.05
        max: 1.25
